name: Lint C++ (GUI)

on:
  push:
    branches:
      - Dev
  pull_request:
    branches:
      - Dev

jobs:
  cpplint:
    runs-on: ubuntu-latest
    steps:
      - name: Retrive code
        uses: actions/checkout@v4

      - name: Python configuration
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install cpplint
        run: pip install cpplint

      - name: Launch cpplint
        run: cpplint --filter=-legal/copyright --recursive gui/
